Repository Gabao-Farias/triple-modular-redundancy, pull requests merged in 2021-10, with the labels that each got.

#7 Feat/statistics integration
  .github/workflows/delpoy.yml
  package.json
  src/App.tsx
  src/components/Results/index.tsx
  src/components/Results/styles.ts
  src/components/Statistics/index.tsx
  src/components/Statistics/styles.ts
  src/components/index.ts
  src/lib/tmr/Statistics/TMRResultStatistics.ts
  src/lib/tmr/TMR.ts
  src/lib/tmr/TMRResult.ts
  src/stores/tmr.store.ts
  src/styles.ts
  src/utils/hooks/index.ts
  src/utils/theme/Breakpoints.ts
  src/utils/theme/Colors.ts
  src/utils/theme/index.ts
  src/utils/types/Charts.d.ts
  src/utils/types/Statistics.d.ts
  yarn.lock
Labels: enhancement

#10 Style/fixes
  src/stores/tmr.store.ts
  src/styles.ts
Labels: bug, enhancement

#17 ClosestMaximum Fix
  src/utils/functions/votationMethod/average.ts
Labels: hotfix
